spring:
  datasource:
    url: jdbc:mysql://localhost:3306/push_to_slack?useUnicode=true&serverTimezone=UTC
#    username: injected from environment e.g. export SPRING_DATASOURCE_USERNAME=user
#    password: injected from environment e.g. export SPRING_DATASOURCE_PASSWORD=secret
    driver-class-name: com.mysql.jdbc.Driver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
